apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-api
data:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  LOG_FORMAT: {{ .Values.env.LOG_FORMAT | quote }}
  PAGE_SIZE: {{ .Values.env.PAGE_SIZE | quote }}
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  ALLOWED_ORIGINS: {{ .Values.env.ALLOWED_ORIGINS | quote }}
