apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  PAGE_SIZE: {{ .Values.env.PAGE_SIZE | quote }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
