apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: bookstore.local     # Replace this with your real domain or add to /etc/hosts for local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookstore-api
                port:
                  number: 8080
