apiVersion: v1
kind: Service
metadata:
  name: bookstore-api
spec:
  type: ClusterIP
  selector:
    app: bookstore-api
  ports:
    - name: http
      port: 8080              # External port (in-cluster service)
      targetPort: http        # Must match container port or name in Deployment
