apiVersion: v1
kind: Service
metadata:
  name: bookstore-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bookstore-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080              # External port (in-cluster service)
      targetPort: http        # Must match container port or name in Deployment
