version: '3.9'

services:
  web:
    build: .
    container_name: bookstore-api
    ports:
      - "${PORT:-8080}:8080"
    # volumes:
    #   - books-data:/app/books.db
    # Use below above for prod but add 
    volumes:
      - .:/app  # Mount code for live reload
    env_file:
      - .env
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port ${PORT:-8080}
      --reload
