replicaCount: 2

image:
  repository: ghcr.io/GabrielPora/docker-pipeline-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: bookstore.local
  path: /
  pathType: Prefix

env:
  APP_ENV: prod
  PAGE_SIZE: "10"
  DATABASE_URL: postgresql://postgres:postgres@bookstore-db:5432/books

resources: {}
