replicaCount: 1

image:
  repository: ghcr.io/gabrielpora/docker-pipeline-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: bookstore.local
  path: /
  pathType: Prefix
  port: 8080

env:
  APP_ENV: dev
  PAGE_SIZE: "10"
  DATABASE_URL: "sqlite:///./books.db"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(levelname)s:%(name)s:%(message)s"
  ALLOWED_ORIGINS: "*"

resources: {}
