image:
  repository: ghcr.io/gabrielpora/docker-pipeline-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: bookstore.local
  path: /
  pathType: Prefix

env:
  APP_ENV: dev
  PAGE_SIZE: "10"
  DATABASE_URL: "sqlite:///./books.db"
  LOG_LEVEL: "INFO"

resources: {}
